/**
 * Curated mini-app and gateway HTTP routes (contract layer).
 * Keep in sync with gateway/index.ts and CloudAppHostService — validated in tests.
 */

import type { PaprApiCatalogEntry } from "./types.js";

const miniApp: PaprApiCatalogEntry[] = [
  {
    id: "db-schema",
    title: "Linked database schema",
    summary: "Column info for linked SQLite sources (app data-sources.json).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "GET",
    path: "/api/db/schema",
    keywords: ["db", "schema", "sqlite", "columns", "table"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "db-query",
    title: "Single read query",
    summary: "One SELECT/WITH against a linked source. Prefer /api/db/batch for multiple reads.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/db/query",
    bodyFields: [
      { name: "appId", description: "Mini-app id (optional in iframe — inferred from Referer)" },
      { name: "sourceId", description: "Linked DB alias from data-sources.json", required: false },
      { name: "sql", description: "SELECT or WITH ... SELECT", required: true },
      { name: "params", description: "Bound parameters array", required: false },
    ],
    keywords: ["db", "query", "select", "read", "sqlite"],
    example: `fetch('/api/db/query', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sql: 'SELECT * FROM leads LIMIT 10', params: [] }) })`,
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "db-batch-read",
    title: "Batch read queries",
    summary: "Up to 25 SELECT/WITH statements in one HTTP round trip. Same contract on desktop and cloud.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/db/batch",
    pathAliases: ["/api/db/query-batch", "/api/db/read-batch"],
    bodyFields: [
      { name: "appId", description: "Mini-app id (optional in iframe)" },
      {
        name: "statements",
        description: "Array of { sourceId?, sql, params? }",
        required: true,
      },
    ],
    limits: ["Max 25 statements per request", "Each sql must be SELECT or WITH ... SELECT"],
    keywords: ["db", "batch", "read-batch", "query-batch", "bulk", "multiple", "select"],
    example: `fetch('/api/db/batch', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ statements: [{ sql: 'SELECT COUNT(*) AS n FROM leads' }, { sql: 'SELECT * FROM settings LIMIT 1' }] }) })`,
    playbookRef: "preloaded-miniapp-contracts",
  },
  {
    id: "db-write",
    title: "Single write statement",
    summary: "One INSERT/UPDATE/DELETE/REPLACE/UPSERT. Prefer write-batch for many rows.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/db/write",
    bodyFields: [
      { name: "sourceId", description: "Linked DB alias", required: false },
      { name: "sql", description: "DML statement", required: true },
      { name: "params", description: "Bound parameters", required: false },
    ],
    keywords: ["db", "write", "insert", "update", "delete", "upsert"],
    example: `fetch('/api/db/write', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sql: 'INSERT INTO leads (name) VALUES (?)', params: ['Acme'] }) })`,
  },
  {
    id: "db-write-batch",
    title: "Batch write statements",
    summary: "Up to 25 DML statements. atomic:true wraps one SQLite transaction (same linked DB only).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/db/write-batch",
    bodyFields: [
      { name: "statements", description: "Array of { sourceId?, sql, params? }", required: true },
      { name: "atomic", description: "If true, all statements in one transaction (same source)", required: false },
    ],
    limits: ["Max 25 statements", "atomic:true requires same sourceId for all statements"],
    keywords: ["db", "write-batch", "bulk", "transaction", "atomic", "batch"],
    example: `fetch('/api/db/write-batch', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ atomic: true, statements: [{ sql: 'INSERT INTO t (k) VALUES (?)', params: ['a'] }, { sql: 'INSERT INTO t (k) VALUES (?)', params: ['b'] }] }) })`,
    playbookRef: "preloaded-miniapp-contracts",
  },
  {
    id: "db-exec",
    title: "DDL / pragma exec",
    summary: "Schema migrations and PRAGMA on linked DBs (restricted). Use app migrations folder for schema owner apps.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/db/exec",
    keywords: ["db", "exec", "ddl", "migration", "pragma"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "jobs-list",
    title: "List jobs",
    summary: "Jobs visible to the mini-app (linked job ids).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "GET",
    path: "/api/jobs/list",
    keywords: ["jobs", "list", "cron", "pipeline"],
  },
  {
    id: "jobs-status",
    title: "Job run status",
    summary: "Latest status for one job id.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "GET",
    path: "/api/jobs/status/:jobId",
    keywords: ["jobs", "status", "running", "failed"],
  },
  {
    id: "jobs-run",
    title: "Run job once",
    summary: "Trigger a linked job immediately (respects auth on cloud).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/jobs/run",
    bodyFields: [{ name: "jobId", description: "Job uuid", required: true }],
    keywords: ["jobs", "run", "trigger", "execute"],
  },
  {
    id: "jobs-create",
    title: "Create job from mini-app",
    summary: "Programmatic job creation (rate limited). Agent equivalent: create_job tool.",
    surfaces: ["mini-app-http"],
    runtimes: ["desktop"],
    method: "POST",
    path: "/api/jobs/create",
    limits: ["10 jobs/minute per app", "command max 100KB"],
    keywords: ["jobs", "create", "dynamic"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "jobs-events-sse",
    title: "Job and DB change SSE",
    summary: "Server-Sent Events for job completion and linked DB changes. Prefer papr.jobs.subscribe SDK wrapper.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "GET",
    path: "/api/jobs/events",
    keywords: ["sse", "events", "subscribe", "live", "refresh", "onDbChanged", "job"],
    playbookRef: "preloaded-miniapp-contracts",
  },
  {
    id: "bash-run",
    title: "Sandboxed bash (mini-app)",
    summary: "Run shell with ${KEY_NAME} substitution server-side. Not full agent bash.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/bash/run",
    bodyFields: [{ name: "command", description: "Shell command string", required: true }],
    keywords: ["bash", "shell", "curl", "psql", "keys"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "app-backend",
    title: "App Python/Node backend actions",
    summary: "POST /api/app/backend/:action — runs handlers in app backend/ folder.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/app/backend/:action",
    keywords: ["backend", "python", "server", "action"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "files-list",
    title: "List App Files",
    summary: "Large binaries stored via App Files (not in SQLite).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "GET",
    path: "/api/files",
    keywords: ["files", "upload", "pdf", "binary", "app files"],
    playbookRef: "src/resources/agent-docs/APP_FILES_GUIDE.md",
  },
  {
    id: "files-ticket-commit",
    title: "Browser upload ticket + commit",
    summary: "Two-step upload for large files from the browser.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/files/ticket",
    pathAliases: ["/api/files/commit", "/api/files/url"],
    keywords: ["files", "upload", "ticket", "commit", "signed url"],
    playbookRef: "src/resources/agent-docs/APP_FILES_GUIDE.md",
  },
  {
    id: "credentials-client-keys",
    title: "Client-side key names",
    summary: "Lists which custom key names exist for substitution (not values).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/credentials/client-keys",
    keywords: ["keys", "credentials", "custom keys"],
  },
  {
    id: "app-agent-sessions",
    title: "Embedded app agent chat",
    summary: "Sessions, messages, SSE stream for in-app assistant bubble.",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["desktop", "cloud"],
    method: "POST",
    path: "/api/app-agent/sessions",
    pathAliases: [
      "/api/app-agent/sessions/:sessionId/messages",
      "/api/app-agent/sessions/:sessionId/stream",
    ],
    keywords: ["agent", "chat", "bubble", "assistant", "app-agent"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "access-members",
    title: "Cloud team access",
    summary: "Who can access published app (cloud host).",
    surfaces: ["mini-app-http", "cloud-gateway"],
    runtimes: ["cloud"],
    method: "GET",
    path: "/api/access",
    pathAliases: ["/api/members"],
    keywords: ["auth", "team", "members", "access"],
  },
];

/** Desktop gateway routes agents use while building (not mini-app iframe). */
const desktopAgent: PaprApiCatalogEntry[] = [
  {
    id: "cloud-publish",
    title: "Publish app to cloud",
    summary: "Read/patch publish config, publish, unpublish — agent tools mirror these.",
    surfaces: ["desktop-gateway"],
    runtimes: ["desktop"],
    method: "GET",
    path: "/api/cloud/publish/:appId",
    pathAliases: [
      "/api/cloud/publish/:appId/readiness",
      "/api/cloud/publish/:appId/compatibility",
    ],
    keywords: ["cloud", "publish", "share", "link"],
    playbookRef: "preloaded-app-and-jobs-guide",
  },
  {
    id: "sync-status",
    title: "Git + Turso sync status",
    summary: "Workspace sync chip data for apps and jobs.",
    surfaces: ["desktop-gateway"],
    runtimes: ["desktop"],
    method: "GET",
    path: "/api/sync/status",
    pathAliases: ["/api/sync/items", "/api/sync/push", "/api/sync/pull"],
    keywords: ["sync", "git", "turso", "cloud"],
  },
  {
    id: "dev-papr-api-catalog",
    title: "Papr API catalog (JSON)",
    summary: "Full generated catalog for debugging; agents should use get_papr_api_reference tool.",
    surfaces: ["desktop-gateway"],
    runtimes: ["desktop"],
    method: "GET",
    path: "/api/dev/papr-api-catalog",
    keywords: ["catalog", "openapi", "docs", "reference"],
  },
];

export const MINI_APP_HTTP_CATALOG_ENTRIES: PaprApiCatalogEntry[] = [
  ...miniApp,
  ...desktopAgent,
];
