/**
 * Canonical Papr workspace root.
 *
 * Desktop: ~/Papr/orgs/{orgId}/namespaces/{namespaceId} (via .active-workspace.json)
 * Legacy fallback: ~/Papr
 * Cloud agent gateway: per-run clone mounted at PAPR_HOME
 */

import os from "os";
import path from "path";
import {
  ensureActiveWorkspaceEnvSynced,
  getPaprBaseDir,
} from "./paprWorkspace.js";

function formatPathForAgent(absolutePath: string): string {
  const home = os.homedir();
  const resolved = path.resolve(absolutePath);
  const prefix = `${home}${path.sep}`;
  if (resolved.startsWith(prefix)) {
    return `~${path.sep}${path.relative(home, resolved)}`;
  }
  return resolved;
}

export function getPaprRoot(): string {
  const override = process.env.PAPR_HOME?.trim();
  const pointer = ensureActiveWorkspaceEnvSynced();

  // Cloud agent runs use ephemeral PAPR_HOME clones — no desktop pointer file.
  if (isCloudAgentGatewayMode() || !pointer?.paprHome) {
    if (override) {
      return path.resolve(override);
    }
    return getPaprBaseDir();
  }

  return path.resolve(pointer.paprHome);
}

export function getPaprJobsRoot(): string {
  return path.join(getPaprRoot(), "Jobs");
}

export function getPaprAppsRoot(): string {
  return path.join(getPaprRoot(), "apps");
}

/**
 * Block direct write_file edits to mini-app trees — agents must use
 * edit_app_file / edit_app_file_lines so esbuild + validation run immediately.
 */
export function getMiniAppWriteBlockReason(resolvedFilePath: string): string | null {
  const appsRoot = path.resolve(getPaprAppsRoot());
  const resolved = path.resolve(resolvedFilePath);
  const prefix = `${appsRoot}${path.sep}`;
  if (!resolved.startsWith(prefix)) {
    return null;
  }

  const rel = path.relative(appsRoot, resolved);
  const segments = rel.split(path.sep);
  if (segments.length < 2 || !segments[0]) {
    return null;
  }

  const appId = segments[0];
  const filename = segments.slice(1).join("/");

  if (/^dist[/\\]/.test(filename)) {
    return (
      `⛔ dist/ is auto-generated by esbuild — do not edit. ` +
      `Fix source files, then validate_app({ appId: "${appId}" }).`
    );
  }

  return (
    `⛔ Use write_file or edit_file for mini-app sources (auto-runs esbuild + validation). ` +
    `Active path: ${formatPathForAgent(path.join(appsRoot, appId, filename))} ` +
    `or write_file({ path: "${formatPathForAgent(path.join(appsRoot, appId, filename))}", content: "..." }).`
  );
}

export function getPaprDataDir(): string {
  return path.join(getPaprRoot(), "data");
}

export function getPaprWorkspaceDir(): string {
  return path.join(getPaprRoot(), "workspace");
}

export function getPaprDocumentsDir(): string {
  return path.join(getPaprRoot(), "documents");
}

export function getPaprBundlesDir(): string {
  return path.join(getPaprRoot(), "bundles");
}

/** Shared Cloud Run agent gateway — no desktop CloudSync / scheduler. */
export function isCloudAgentGatewayMode(): boolean {
  return process.env.GATEWAY_MODE === "cloud_agent";
}
