/**
 * Canonical Papr workspace root.
 *
 * Desktop: ~/Papr
 * Cloud agent gateway: per-run clone mounted at PAPR_HOME
 */

import os from "os";
import path from "path";

export function getPaprRoot(): string {
  const override = process.env.PAPR_HOME?.trim();
  if (override) {
    return path.resolve(override);
  }
  return path.join(os.homedir(), "Papr");
}

export function getPaprJobsRoot(): string {
  return path.join(getPaprRoot(), "Jobs");
}

export function getPaprAppsRoot(): string {
  return path.join(getPaprRoot(), "apps");
}

/**
 * Block direct write_file edits to mini-app trees — agents must use
 * edit_app_file / edit_app_file_lines so esbuild + validation run immediately.
 */
export function getMiniAppWriteBlockReason(resolvedFilePath: string): string | null {
  const appsRoot = path.resolve(getPaprAppsRoot());
  const resolved = path.resolve(resolvedFilePath);
  const prefix = `${appsRoot}${path.sep}`;
  if (!resolved.startsWith(prefix)) {
    return null;
  }

  const rel = path.relative(appsRoot, resolved);
  const segments = rel.split(path.sep);
  if (segments.length < 2 || !segments[0]) {
    return null;
  }

  const appId = segments[0];
  const filename = segments.slice(1).join("/");

  if (/^dist[/\\]/.test(filename)) {
    return (
      `⛔ dist/ is auto-generated by esbuild — do not edit. ` +
      `Fix source files, then validate_app({ appId: "${appId}" }).`
    );
  }

  return (
    `⛔ Use edit_file for mini-app sources (auto-runs esbuild + validation). ` +
    `Example: edit_file({ path: "~/Papr/apps/${appId}/${filename}", oldString: "...", newString: "..." })`
  );
}

export function getPaprDataDir(): string {
  return path.join(getPaprRoot(), "data");
}

/** Shared Cloud Run agent gateway — no desktop CloudSync / scheduler. */
export function isCloudAgentGatewayMode(): boolean {
  return process.env.GATEWAY_MODE === "cloud_agent";
}
