/**
 * Resolve an absolute file path to a Papr mini-app, job, or external target.
 */

import path from "path";
import { getPaprAppsRoot, getPaprJobsRoot } from "./paprRoot.js";

export type EditFileTarget =
  | {
      kind: "mini_app";
      appId: string;
      filename: string;
      resolvedPath: string;
    }
  | {
      kind: "job";
      jobId: string;
      filename: string;
      resolvedPath: string;
    }
  | {
      kind: "external";
      resolvedPath: string;
    };

export function resolveEditFileTarget(
  resolvedPath: string,
): EditFileTarget | { kind: "blocked"; reason: string } {
  const resolved = path.resolve(resolvedPath);

  const appsRoot = path.resolve(getPaprAppsRoot());
  const appsPrefix = `${appsRoot}${path.sep}`;
  if (resolved.startsWith(appsPrefix)) {
    const rel = path.relative(appsRoot, resolved);
    const parts = rel.split(path.sep);
    if (parts.length >= 2 && parts[0]) {
      const appId = parts[0];
      const filename = parts.slice(1).join("/");
      if (/^dist[/\\]/.test(filename)) {
        return {
          kind: "blocked",
          reason:
            `⛔ dist/ is auto-generated by esbuild — do not edit. ` +
            `Fix source files for app ${appId}, then validate_app({ appId: "${appId}" }).`,
        };
      }
      return { kind: "mini_app", appId, filename, resolvedPath: resolved };
    }
    return {
      kind: "blocked",
      reason: `Invalid mini-app path: expected $PAPR_HOME/apps/{appId}/{filename}`,
    };
  }

  const jobsRoot = path.resolve(getPaprJobsRoot());
  const jobsPrefix = `${jobsRoot}${path.sep}`;
  if (resolved.startsWith(jobsPrefix)) {
    const rel = path.relative(jobsRoot, resolved);
    const parts = rel.split(path.sep);
    if (parts.length >= 2 && parts[0]) {
      const jobId = parts[0];
      const filename = parts.slice(1).join("/");
      return { kind: "job", jobId, filename, resolvedPath: resolved };
    }
    return {
      kind: "blocked",
      reason: `Invalid job path: expected $PAPR_HOME/Jobs/{jobId}/{filename}`,
    };
  }

  return { kind: "external", resolvedPath: resolved };
}
