import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import type { ToolResult } from "../types/index.js";
import { getCurrentChatId, getJobToolEnv } from "./context.js";
import type { GeneratedMediaArtifact } from "../../gateway/services/mediaGeneration/types.js";

function unwrapContext<T>(input: T | { context?: T }): T {
  if (input && typeof input === "object" && "context" in input) {
    return (input as { context?: T }).context ?? (input as T);
  }
  return input as T;
}

const APP_FILES_WIRING_REMINDER =
  "⚠️ MINI-APP IMAGES: Re-run generate_media with appId to register in App Files. " +
  "Do NOT read_file/jpeg into context, embed base64, or curl invented routes like /api/apps/{id}/app-files/{id}. " +
  "Correct: store appFileId in SQLite; mini-app uses papr.files.url(id). " +
  "See APP_FILES_GUIDE.md § Agent-generated images.";

function buildNextStep(artifact: GeneratedMediaArtifact): string {
  if (artifact.appFileId && artifact.appId) {
    return (
      `Store appFileId "${artifact.appFileId}" in SQLite (not localPath). ` +
      `Mini-app: import { papr } from '/__papr__/papr-files.js'; ` +
      `const { url } = await papr.files.url('${artifact.appFileId}'); img.src = url. ` +
      `Do NOT read_file the image or embed base64. ` +
      `Gateway URL (debug only): POST /api/files/url body { appId: "${artifact.appId}", id: "${artifact.appFileId}" }.`
    );
  }

  return (
    "Chat-only output (no appFileId). For mini-app decks/UI, re-run with appId to register in App Files. " +
    "Never wire images via base64 or by reading JPEGs into agent context."
  );
}

function buildGenerateMediaData(artifact: GeneratedMediaArtifact): Record<string, unknown> {
  const mediaLabel = artifact.kind === "video" ? "video" : "image";
  const nextStep = buildNextStep(artifact);
  const message = artifact.appFileId
    ? `Generated ${mediaLabel} registered as App File ${artifact.appFileId}. Store that id in your database — not the local path.`
    : `Generated ${mediaLabel} saved to ${artifact.localPath}. Pass appId to register in App Files for published mini-apps.`;

  return {
    appFileId: artifact.appFileId ?? null,
    appId: artifact.appId ?? null,
    fileName: artifact.fileName,
    kind: artifact.kind,
    mimeType: artifact.mimeType,
    sizeBytes: artifact.sizeBytes,
    localPath: artifact.localPath,
    modelId: artifact.modelId,
    nextStep,
    message,
    authPath: artifact.authPath,
    sha256Prefix: artifact.sha256Prefix,
  };
}

const aspectRatioSchema = z
  .enum(["1:1", "3:4", "4:3", "9:16", "16:9", "3:2", "2:3"])
  .optional()
  .describe("Output aspect ratio when the model supports it.");

export const listMediaModelsTool = createTool({
  id: "list_media_models",
  description:
    "List image/video generation models available to generate_media, filtered by configured auth (Google API key, OpenAI Platform key, or ChatGPT OAuth). " +
    "Call this before generate_media when you need to pick a model or explain options to the user.",
  inputSchema: z.object({}),
  execute: async (_input): Promise<ToolResult> => {
    const startTime = performance.now();
    try {
      const { listAvailableMediaModels } = await import(
        "../../gateway/services/mediaGeneration/MediaGenerationService.js"
      );
      const data = await listAvailableMediaModels();
      return {
        success: true,
        data,
        duration: performance.now() - startTime,
        timestamp: new Date().toISOString(),
      };
    } catch (error) {
      throw new Error(
        JSON.stringify({
          success: false,
          error: (error as Error).message,
          duration: performance.now() - startTime,
          timestamp: new Date().toISOString(),
        }),
      );
    }
  },
});

export const generateMediaTool = createTool({
  id: "generate_media",
  description:
    "Generate an image or video using a configured provider model. " +
    "Google models use GOOGLE_API_KEY; OpenAI images use Platform API key OR ChatGPT Plus/Pro OAuth (Codex image_generation). " +
    "For mini-apps: ALWAYS pass appId — output registers in App Files and returns appFileId (store in SQLite; mini-app uses papr.files.url(id)). " +
    "Do NOT copy generated bytes into apps/{id}/ code, read_file JPEGs, or embed base64. " +
    "Use list_media_models first to see which models and auth paths are available. " +
    "Prefer this over bash+curl — keys stay server-side and output is stored reliably.",
  inputSchema: z.object({
    prompt: z
      .string()
      .min(1)
      .max(8000)
      .describe("Text prompt describing the image or video to generate."),
    modelId: z
      .string()
      .min(1)
      .describe(
        "Model id from list_media_models (e.g. gemini-3.1-flash-image, gpt-image-2.5-flare, gpt-image-2.5-sunburst, gpt-image-2, veo-3.1-generate-preview).",
      ),
    aspectRatio: aspectRatioSchema,
    durationSeconds: z
      .number()
      .int()
      .min(4)
      .max(8)
      .optional()
      .describe("Video clip length in seconds (Veo models only; default 8)."),
    appId: z
      .string()
      .uuid()
      .optional()
      .describe(
        "REQUIRED for mini-app assets. Registers output in App Files and returns appFileId. Auto-detected from linked agent jobs when omitted.",
      ),
    fileName: z
      .string()
      .min(1)
      .max(120)
      .optional()
      .describe("Optional output filename (extension added if missing)."),
    referenceImagePath: z
      .string()
      .optional()
      .describe(
        "Optional local image path for Gemini image editing / conditioning (absolute or ~/ path).",
      ),
  }),
  execute: async (input): Promise<ToolResult> => {
    const args = unwrapContext(input);
    const startTime = performance.now();

    try {
      const {
        generateMedia,
        resolveAppIdForMediaJob,
      } = await import(
        "../../gateway/services/mediaGeneration/MediaGenerationService.js"
      );

      const chatId = getCurrentChatId();
      const jobEnv = getJobToolEnv();
      const appId =
        (await resolveAppIdForMediaJob(args.appId, chatId)) ?? args.appId;

      const artifact = await generateMedia(
        {
          prompt: args.prompt,
          modelId: args.modelId,
          aspectRatio: args.aspectRatio,
          durationSeconds: args.durationSeconds,
          appId,
          fileName: args.fileName,
          referenceImagePath: args.referenceImagePath,
        },
        { jobDir: jobEnv.JOB_DIR },
      );

      const data = buildGenerateMediaData(artifact);

      return {
        success: true,
        data,
        ...(artifact.appFileId
          ? {}
          : { _appFilesReminder: APP_FILES_WIRING_REMINDER }),
        duration: performance.now() - startTime,
        timestamp: new Date().toISOString(),
      };
    } catch (error) {
      throw new Error(
        JSON.stringify({
          success: false,
          error: (error as Error).message,
          duration: performance.now() - startTime,
          timestamp: new Date().toISOString(),
        }),
      );
    }
  },
});

export const mediaGenerationTools = [listMediaModelsTool, generateMediaTool];
