/**
 * Which app files a contribute-back proposal may carry.
 *
 * Build outputs are regenerated by the owner's publish, and metadata.json
 * holds per-copy details (title suffix, tags, updatedAt, ids). Shipping them
 * makes every two concurrent proposals "conflict" on files nobody edited, so
 * they are left out and the merged branch keeps the owner's versions.
 */

const EXCLUDED_PREFIXES = ["dist/", "__papr__/"];

const EXCLUDED_FILES = new Set([
  "backend/bundle.json",
  "metadata.json",
  // Fully generated from data-sources.json (AppService.ensureAppDbTs) and
  // rebuilt after every pull / link, so it is never an edit and never shipped.
  "db.ts",
  // Cloud-prep markers, rewritten per copy on every publish.
  ".papr-cloud-revision",
  "data/cloud-repo-head.txt",
]);

export function isProposalExcludedAppPath(relativePath: string): boolean {
  const rel = relativePath.replace(/\\/g, "/").replace(/^\.\//, "");
  if (EXCLUDED_FILES.has(rel)) return true;
  return EXCLUDED_PREFIXES.some((prefix) => rel.startsWith(prefix));
}

/**
 * Build outputs a direct publish (Maintainer/Admin) must carry: nobody rebuilds
 * them on the publisher's side afterwards, unlike an accepted proposal.
 */
const BUILD_OUTPUT_FILES = new Set(["backend/bundle.json", "__papr__/app-meta.json"]);
export function isBuildOutputAppPath(relativePath: string): boolean {
  const rel = relativePath.replace(/\\/g, "/").replace(/^\.\//, "");
  return rel.startsWith("dist/") || BUILD_OUTPUT_FILES.has(rel);
}

/** Drop excluded paths in place; returns the removed paths (sorted). */
export function stripProposalExcludedAppFiles(files: Map<string, string>): string[] {
  const removed: string[] = [];
  for (const rel of [...files.keys()]) {
    if (isProposalExcludedAppPath(rel)) {
      files.delete(rel);
      removed.push(rel);
    }
  }
  return removed.sort();
}
