/**
 * Per-file rules for collaborator proposals and pulls.
 *
 * A few app files are written by the installer or by this machine, not by the
 * collaborator: data-sources.json (absolute dbPaths, dropped job links),
 * linked-databases.json (replica push state), the README stub, job.json
 * (local schedule toggle, runtime fields). Shipping them whole reverts the
 * publisher's versions; ignoring them entirely loses real additions (a new
 * database or job link). So they are merged entry-by-entry instead.
 */

import { parseMonolithicJobJson } from "../jobs/jobRuntimeFields.js";

export const DATA_SOURCES_FILE = "data-sources.json";
export const LINKED_DATABASES_FILE = "linked-databases.json";

/** Regenerated by cloud prep on every publish; never proposed or pulled. */
export const REGENERATED_FILES = new Set(["linked-databases.json", "papr-cloud-dependencies.json"]);

/** Scratch / backup files that must never leave the machine. */
export function isLocalScratchPath(rel: string, opts: { job?: boolean } = {}): boolean {
  const norm = rel.replace(/\\/g, "/");
  const segments = norm.split("/");
  const base = segments[segments.length - 1] ?? "";
  if (segments.some((s) => s === "__pycache__" || s === "node_modules" || s === ".venv" || s === "venv")) {
    return true;
  }
  // Job folders keep run output in data/ and logs/; app folders may ship data/.
  if (opts.job && (segments[0] === "data" || segments[0] === "logs")) return true;
  if (base === "job.runtime.json") return true;
  if (/\.(pyc|log|db|db-wal|db-shm|wal|shm|sqlite|sqlite3)$/i.test(base)) return true;
  // foo.py.bak, foo.py.bak-20260926, foo.orig, foo~
  if (/\.(bak|orig|rej|tmp|swp)([-.].*)?$/i.test(base) || base.endsWith("~")) return true;
  return false;
}

/** The installer's placeholder README ("# app-<id>\nPapr app repo: <id>"). */
export function isReadmeStub(content: string | undefined): boolean {
  if (content === undefined) return false;
  const trimmed = content.trim();
  return /^# app-[0-9a-f-]{36}\s*\n\s*Papr app repo: [0-9a-f-]{36}$/i.test(trimmed);
}

interface DataSourceEntry {
  id?: string;
  dbId?: string;
  jobId?: string;
  dbPath?: string;
  [key: string]: unknown;
}

function parseSources(raw: string | undefined): { sources: DataSourceEntry[]; extra: Record<string, unknown> } | null {
  if (raw === undefined) return null;
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (Array.isArray(parsed)) return { sources: parsed as DataSourceEntry[], extra: {} };
    if (parsed && typeof parsed === "object" && Array.isArray((parsed as { sources?: unknown }).sources)) {
      const { sources, ...extra } = parsed as { sources: DataSourceEntry[] };
      return { sources, extra };
    }
  } catch {
    /* unparseable */
  }
  return null;
}

function sourceKey(s: DataSourceEntry): string {
  return s.id ?? s.dbId ?? s.jobId ?? JSON.stringify(s);
}

/**
 * Proposal: the publisher's data-sources.json plus any source the collaborator
 * linked that the publisher doesn't have (portable: dbPath ""). Sources the
 * installer dropped locally are NOT removed from the publisher's file.
 * Returns null when nothing new was linked.
 */
export function dataSourcesForProposal(baseRaw: string | undefined, localRaw: string | undefined): string | null {
  const local = parseSources(localRaw);
  if (!local) return null;
  const base = parseSources(baseRaw) ?? { sources: [], extra: {} };
  const known = new Set(base.sources.map(sourceKey));
  // Job databases are job scratch on the contributor's machine, never shared
  // app data (registry databases carry a dbId; job scratch only a jobId).
  const added = local.sources
    .filter((s) => !known.has(sourceKey(s)) && !(s.jobId && !s.dbId))
    .map((s) => ({ ...s, dbPath: "" }));
  if (added.length === 0) return null;
  return JSON.stringify({ ...base.extra, sources: [...base.sources, ...added] }, null, 2);
}

/**
 * Pull: keep this machine's sources (and their local dbPaths) and add any
 * source the publisher linked since. Returns null when nothing changes.
 */
export function dataSourcesForPull(localRaw: string | undefined, upstreamRaw: string): string | null {
  const upstream = parseSources(upstreamRaw);
  if (!upstream) return null;
  const local = parseSources(localRaw);
  if (!local) return upstreamRaw;
  const known = new Set(local.sources.map(sourceKey));
  const added = upstream.sources.filter((s) => !known.has(sourceKey(s)));
  if (added.length === 0) return null;
  return JSON.stringify({ ...local.extra, sources: [...local.sources, ...added] }, null, 2);
}

/** Replica / machine bookkeeping on a registry record — never shared. */
const MACHINE_DB_FIELDS = [
  "localPath",
  "lastReplicaPushError",
  "lastReplicaPushAt",
  "lastReplicaLocalMutationAt",
  "cutoverAt",
  "cutoverInProgress",
  "cutoverStartedAt",
  "cutoverBlocked",
  "cutoverBlockReason",
];

/**
 * Proposal: publisher's linked-databases.json plus records for databases the
 * collaborator newly linked (machine fields stripped). Null when none.
 */
export function linkedDatabasesForProposal(baseRaw: string | undefined, localRaw: string | undefined): string | null {
  if (localRaw === undefined) return null;
  let local: { databases?: Record<string, Record<string, unknown>> };
  try {
    local = JSON.parse(localRaw);
  } catch {
    return null;
  }
  let base: { version?: number; databases?: Record<string, Record<string, unknown>> } = { version: 1, databases: {} };
  try {
    if (baseRaw !== undefined) base = JSON.parse(baseRaw);
  } catch {
    /* treat as empty */
  }
  const baseDbs = base.databases ?? {};
  const added: Record<string, Record<string, unknown>> = {};
  for (const [dbId, record] of Object.entries(local.databases ?? {})) {
    if (dbId in baseDbs) continue;
    const clean: Record<string, unknown> = { ...record };
    for (const field of MACHINE_DB_FIELDS) delete clean[field];
    clean.localPath = "";
    added[dbId] = clean;
  }
  if (Object.keys(added).length === 0) return null;
  return `${JSON.stringify({ version: base.version ?? 1, databases: { ...baseDbs, ...added } }, null, 2)}\n`;
}

/**
 * Job config fields a collaborator can propose. Runtime fields, ids, timestamps
 * and executionCapability (set per machine) are not proposals.
 */
const PROPOSABLE_JOB_FIELDS = [
  "name",
  "command",
  "requirements",
  "platformCdp",
  "requiredKeys",
  "dependsOn",
  "runtimeCalls",
  "retries",
  "retentionDays",
  "outputMode",
  "outputSchema",
  "maxTurns",
  "memoryPolicy",
  "provider",
  "model",
  "writeDbIds",
  "folder",
  "deliver",
  "recipe",
] as const;

function stable(value: unknown): string {
  // An empty list is the same as no list: installers and older builds add
  // `runtimeCalls: []` / `dependsOn: []`, which is not an edit.
  if (Array.isArray(value) && value.length === 0) return "null";
  return JSON.stringify(value ?? null);
}

/**
 * Proposal: apply the collaborator's deliberate job.json edits onto the
 * publisher's job.json, field by field. A field missing locally (the
 * installer dropped it) is not a removal. schedule.enabled is a per-machine
 * toggle; only a changed cron is proposed. Returns null when nothing changed.
 */
export function jobJsonForProposal(baseRaw: string | undefined, localRaw: string | undefined): string | null {
  if (localRaw === undefined) return null;
  let localObj: Record<string, unknown>;
  try {
    localObj = parseMonolithicJobJson(JSON.parse(localRaw) as Record<string, unknown>).config as Record<string, unknown>;
  } catch {
    return null;
  }
  if (baseRaw === undefined) {
    // New job: ship its config as-is (minus runtime fields).
    return `${JSON.stringify(localObj, null, 2)}\n`;
  }
  let baseObj: Record<string, unknown>;
  try {
    baseObj = JSON.parse(baseRaw) as Record<string, unknown>;
  } catch {
    return null;
  }
  const next: Record<string, unknown> = { ...baseObj };
  let changed = false;
  for (const field of PROPOSABLE_JOB_FIELDS) {
    if (!(field in localObj)) continue;
    if (stable(localObj[field]) === stable(baseObj[field])) continue;
    next[field] = localObj[field];
    changed = true;
  }
  const localCron = (localObj.schedule as { cron?: string } | undefined)?.cron;
  const baseSchedule = baseObj.schedule as { cron?: string; enabled?: boolean } | undefined;
  if (localCron && localCron !== baseSchedule?.cron) {
    next.schedule = { ...(baseSchedule ?? { enabled: false }), cron: localCron };
    changed = true;
  }
  return changed ? `${JSON.stringify(next, null, 2)}\n` : null;
}
